"""empty message

Revision ID: 3d518831b55b
Revises: eb8483126e78
Create Date: 2025-08-01 03:22:05.717808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d518831b55b'
down_revision = 'eb8483126e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table60b')
    with op.batch_alter_table('oil_tonnages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Tonnage', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oil_tonnages', schema=None) as batch_op:
        batch_op.drop_column('Tonnage')

    op.create_table('table60b',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.Column('density', sa.NUMERIC(), nullable=True),
    sa.Column('Temperature', sa.NUMERIC(), nullable=True),
    sa.Column('vcf', sa.REAL(), nullable=True),
    sa.Column('class', sa.NullType(), nullable=True),
    sa.Column('vcf2', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
