"""empty message

Revision ID: 45d6c2fd34db
Revises: 67b179bfbd69
Create Date: 2025-08-03 18:29:33.157259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d6c2fd34db'
down_revision = '67b179bfbd69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oil_tonnages', schema=None) as batch_op:
        batch_op.alter_column('volume',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
        batch_op.alter_column('density',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
        batch_op.alter_column('temperature',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
        batch_op.alter_column('vcf',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=True)
        batch_op.alter_column('Tonnage',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oil_tonnages', schema=None) as batch_op:
        batch_op.alter_column('Tonnage',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('vcf',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('temperature',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('density',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('volume',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
