"""empty message

Revision ID: 5dfc08d17d6b
Revises: 5f579f0be01e
Create Date: 2025-08-03 16:12:31.337093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfc08d17d6b'
down_revision = '5f579f0be01e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oil_tonnages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Numeric(), nullable=False))
        batch_op.drop_column('Temperature')

    with op.batch_alter_table('table60b', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Numeric(), nullable=True))
        batch_op.drop_column('Temperature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table60b', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Temperature', sa.NUMERIC(), nullable=True))
        batch_op.drop_column('temperature')

    with op.batch_alter_table('oil_tonnages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Temperature', sa.NUMERIC(), nullable=False))
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###
