"""empty message

Revision ID: 5f579f0be01e
Revises: 3d518831b55b
Create Date: 2025-08-02 18:22:58.228189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f579f0be01e'
down_revision = '3d518831b55b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table60b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('density', sa.Numeric(), nullable=True),
    sa.Column('Temperature', sa.Numeric(), nullable=True),
    sa.Column('vcf', sa.Numeric(), nullable=True),
    sa.Column('class', sa.Numeric(), nullable=True),
    sa.Column('vcf2', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table60b')
    # ### end Alembic commands ###
