"""empty message

Revision ID: 67b179bfbd69
Revises: 783fb5e464a1
Create Date: 2025-08-03 18:21:45.933734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b179bfbd69'
down_revision = '783fb5e464a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oil_tonnages', schema=None) as batch_op:
        batch_op.alter_column('vcf',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('Tonnage',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oil_tonnages', schema=None) as batch_op:
        batch_op.alter_column('Tonnage',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('vcf',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    # ### end Alembic commands ###
