"""empty message

Revision ID: 783fb5e464a1
Revises: b0f44e7d282e
Create Date: 2025-08-03 18:20:57.123022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783fb5e464a1'
down_revision = 'b0f44e7d282e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oil_tonnages', schema=None) as batch_op:
        batch_op.alter_column('volume',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('density',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('temperature',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oil_tonnages', schema=None) as batch_op:
        batch_op.alter_column('temperature',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('density',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('volume',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
