"""empty message

Revision ID: 88399cda2f1d
Revises: 5dfc08d17d6b
Create Date: 2025-08-03 16:20:26.703928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88399cda2f1d'
down_revision = '5dfc08d17d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table60b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('density', sa.Numeric(), nullable=True),
    sa.Column('temperature', sa.Numeric(), nullable=True),
    sa.Column('vcf', sa.Numeric(), nullable=True),
    sa.Column('class', sa.Numeric(), nullable=True),
    sa.Column('vcf2', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table60b')
    # ### end Alembic commands ###
