"""empty message

Revision ID: a449ee7518b9
Revises: 
Create Date: 2025-08-04 10:55:50.131718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a449ee7518b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oil_tonnages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('density', sa.Numeric(), nullable=False),
    sa.Column('temperature', sa.Numeric(), nullable=False),
    sa.Column('vcf', sa.Numeric(), nullable=True),
    sa.Column('Tonnage', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table60b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('density', sa.Numeric(), nullable=True),
    sa.Column('temperature', sa.Numeric(), nullable=True),
    sa.Column('vcf', sa.Numeric(), nullable=True),
    sa.Column('class', sa.Numeric(), nullable=True),
    sa.Column('vcf2', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table60b')
    op.drop_table('oil_tonnages')
    # ### end Alembic commands ###
