"""empty message

Revision ID: b0f44e7d282e
Revises: 88399cda2f1d
Create Date: 2025-08-03 16:29:59.378971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f44e7d282e'
down_revision = '88399cda2f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table60b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('density', sa.Numeric(), nullable=True),
    sa.Column('temperature', sa.Numeric(), nullable=True),
    sa.Column('vcf', sa.Numeric(), nullable=True),
    sa.Column('class', sa.Numeric(), nullable=True),
    sa.Column('vcf2', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oil_tonnages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('volume',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
        batch_op.drop_column('pid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oil_tonnages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pid', sa.INTEGER(), nullable=False))
        batch_op.alter_column('volume',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('id')

    op.drop_table('table60b')
    # ### end Alembic commands ###
