"""empty message

Revision ID: eb8483126e78
Revises: 
Create Date: 2025-08-01 01:46:51.282565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8483126e78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oil_tonnages',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('density', sa.Numeric(), nullable=False),
    sa.Column('Temperature', sa.Numeric(), nullable=False),
    sa.Column('vcf', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.drop_table('table60b')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table60b',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.Column('density', sa.NUMERIC(), nullable=True),
    sa.Column('Temperature', sa.NUMERIC(), nullable=True),
    sa.Column('vcf', sa.REAL(), nullable=True),
    sa.Column('class', sa.NullType(), nullable=True),
    sa.Column('vcf2', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('oil_tonnages')
    # ### end Alembic commands ###
